# Generated by Django 5.0 on 2026-04-20 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Type d'action (ex: CONSULTER_CONSOMMATION, ACQUITTER_ANOMALIE)", max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Details supplementaires en JSON (foyer_id, anomalie_id, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Journal d'action",
                'verbose_name_plural': "Journaux d'actions",
                'db_table': 'energy_actionlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquittee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acquittee_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'energy_alerte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_confiance', models.FloatField(help_text="Score de confiance de l'anomalie [0.0, 1.0]", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('severite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('CONSULTEE', 'Consultee'), ('ACQUITTEE', 'Acquittee')], default='NOUVELLE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'db_table': 'energy_anomalie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Heure de la mesure')),
                ('kwh', models.FloatField(help_text='Consommation en kWh')),
                ('anomaly_label', models.CharField(blank=True, help_text="Label d'anomalie detecte par ML", max_length=50, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature ambiante en degres C', null=True)),
            ],
            options={
                'verbose_name': 'Consommation',
                'verbose_name_plural': 'Consommations',
                'db_table': 'energy_consommation',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Conversation IA',
                'verbose_name_plural': 'Conversations IA',
                'db_table': 'energy_conversationIA',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_foyer', models.CharField(db_index=True, max_length=50, unique=True)),
                ('adresse', models.TextField()),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('puissance_souscrite', models.FloatField(help_text='Puissance souscrite en kW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Foyer',
                'verbose_name_plural': 'Foyers',
                'db_table': 'energy_foyer',
                'ordering': ['numero_foyer'],
            },
        ),
    ]
