# Generated by Django 5.0 on 2026-04-20 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='anomalie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerte', to='energy.anomalie'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='consommation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomalie', to='energy.consommation'),
        ),
        migrations.AddField(
            model_name='conversationia',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_ia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consommation',
            name='foyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='energy.foyer'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['utilisateur', '-timestamp'], name='energy_acti_utilisa_516fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['action', '-timestamp'], name='energy_acti_action_bbd4de_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['acquittee', '-created_at'], name='energy_aler_acquitt_0931cc_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['statut', '-created_at'], name='energy_anom_statut_78c01c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationia',
            index=models.Index(fields=['utilisateur', '-timestamp'], name='energy_conv_utilisa_4a7519_idx'),
        ),
        migrations.AddIndex(
            model_name='consommation',
            index=models.Index(fields=['foyer', '-timestamp'], name='energy_cons_foyer_i_1e3843_idx'),
        ),
        migrations.AddIndex(
            model_name='consommation',
            index=models.Index(fields=['timestamp'], name='energy_cons_timesta_0d1742_idx'),
        ),
    ]
