# Generated by Django 5.0 on 2026-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consommation",
            name="anomaly_label",
            field=models.CharField(
                blank=True,
                help_text="Label d'anomalie détecté par ML (ex: 'pic', 'anomalie_consommation')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consommation",
            name="temperature",
            field=models.FloatField(
                blank=True, help_text="Température ambiante en °C", null=True
            ),
        ),
    ]
