# Generated by Django 5.0.14 on 2026-05-07 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_sprint3_anomalies_alertes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alerte',
            new_name='energy_aler_statut_ccac5a_idx',
            old_name='energy_alrt_statut_created_idx',
        ),
        migrations.RenameIndex(
            model_name='alerte',
            new_name='energy_aler_anomali_712bb8_idx',
            old_name='energy_alrt_anomal_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='anomalie',
            new_name='energy_anom_consomm_ba0d48_idx',
            old_name='energy_anom_consumm_statut_idx',
        ),
        migrations.AlterField(
            model_name='alerte',
            name='acquittee',
            field=models.BooleanField(default=False, help_text='Alerte acquittée (archivée)'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='score_confiance',
            field=models.FloatField(help_text='Score de confiance Hugging Face [0.0, 1.0]', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
