# Generated by Django 5.0 on 2026-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_consumptionreading'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consumptionreading',
            new_name='energy_cons_residen_6de389_idx',
            old_name='energy_cons_resident_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='consumptionreading',
            new_name='energy_cons_meter_i_41107f_idx',
            old_name='energy_cons_meter_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='consumptionreading',
            new_name='energy_cons_timesta_4f5cbc_idx',
            old_name='energy_cons_timestamp_idx',
        ),
    ]
