# Generated by Django 5.0 on 2026-04-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0003_alter_consommation_anomaly_label_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="foyer",
            field=models.ForeignKey(
                blank=True,
                help_text="Foyer associé. Nullable pour les administrateurs (RG3)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilisateurs",
                to="energy.foyer",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("RESIDENT", "Résident"), ("ADMIN", "Administrateur")],
                default="RESIDENT",
                help_text="Le rôle détermine les permissions d'accès (RG2)",
                max_length=20,
            ),
        ),
    ]
