# Generated by Django 5.0 on 2026-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_managed_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_managed_33327b_idx',
            old_name='users_user_managed_idx',
        ),
    ]
